# This is a basic workflow to help you get started with Actions

name: Build with Webpack and Publish to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a first job called "build"
  build:
    # define permissions
    permissions:
      contents: read
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v4

    # Sets up Node
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    # Builds
    - name: Build with Webpack
      run: |
        npm ci
        npx webpack

    # upload generated files
    - name: Upload generated files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  # a second job, to deploy
  deploy:
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: $

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
